FROM arm32v7/debian:stretch

LABEL description="Mosquitto MQTT Broker"
LABEL version="1.0"

RUN apt-get update

RUN apt-get -y install apt-transport-https ca-certificates wget gnupg2

RUN wget http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key && \
    apt-key add mosquitto-repo.gpg.key && \
    rm -f mosquitto-repo.gpg.key && \
    cd /etc/apt/sources.list.d/ && \
    wget http://repo.mosquitto.org/debian/mosquitto-jessie.list

RUN apt-get -y install mosquitto

EXPOSE 1883

CMD /usr/sbin/mosquitto