FROM nodered/node-red-docker:rpi

LABEL description="NodeRed"
LABEL version="1.0"

RUN npm install node-red-dashboard

RUN npm install node-red-contrib-pushover

RUN npm install node-red-node-openweathermap