version: '3'

services:
    fhem:
        restart: always
        ports:
            - "8083:8083"
            - "7072:7072"
        image: fhem/fhem:latest
        volumes:
            - ~/smarthome-docker/container/fhem/:/opt/fhem/
        networks:
            - smarthome-network
        environment:
            FHEM_UID: 1000
            FHEM_GID: 1000
            TIMEOUT: 10
            RESTART: 1
            TELNETPORT: 7072
            TZ: Europe/Berlin
        depends_on:
            - "mqtt"

    mqtt:
        restart: always
        expose:
            - "1883"
            - "9001"
        ports:
            - "1883:1883"
            - "9001:9001"
        build: ./mqtt
        networks:
            - smarthome-network
        volumes:
            - ~/smarthome-docker/container/mqtt/config/:/mosquitto/config/
            - ~/smarthome-docker/container/mqtt/log/:/mosquitto/log/
            - ~/smarthome-docker/container/mqtt/data/:/mosquitto/data/

    nodered:
        restart: always
        expose:
            - "1880"
        ports:
            - "1880:1880"
        build: ./nodered
        user: "1000:1000"
        volumes:
            - ~/smarthome-docker/container/nodered/data/:/data/
        networks:
            - smarthome-network
        depends_on:
            - "mqtt"

    zigbee2mqtt:
        restart: always
        image: koenkk/zigbee2mqtt
        volumes:
            - ~/smarthome-docker/container/zigbee2mqtt/data:/app/data
            - /run/udev:/run/udev:ro
        networks:
            - smarthome-network
        environment:
            TZ: Europe/Amsterdam
        privileged: true
        devices:
            - /dev/ttyACM0:/dev/ttyACM0
        depends_on:
            - "mqtt"

    homebridge:
        restart: always
        build: ./homebridge
        volumes:
            - ~/smarthome-docker/container/homebridge:/homebridge
        network_mode: host
        environment:
             - PGID=1000
             - PUID=1000
             - HOMEBRIDGE_CONFIG_UI=1
             - HOMEBRIDGE_CONFIG_UI_PORT=8080
             - TZ=Europe/Amsterdam
        depends_on:
            - "mqtt"

    influxdb:
        restart: always
        image: influxdb:latest
        volumes:
            - ~/smarthome-docker/container/influxdb:/var/lib/influxdb
        expose:
            - "8086"
        ports:
            - "8086:8086"
        networks:
            - smarthome-network
        environment:
            INFLUXDB_DB: smarthome
            INFLUXDB_USER: telegraf
            INFLUXDB_USER_PASSWORD: telegraf
            INFLUXDB_ADMIN_USER: admin
            INFLUXDB_ADMIN_PASSWORD: secret
            INFLUXDB_HTTP_FLUX_ENABLED: "true"
        
    grafana:
        restart: always
        image: grafana/grafana:latest
        user: "1000:1000"
        volumes:
            - ~/smarthome-docker/container/grafana:/var/lib/grafana
        expose:
            - "3000"
        ports:
            - "3000:3000"
        networks:
            - smarthome-network
        environment:
           GF_SECURITY_ALLOW_EMBEDDING: "true"

    telegraf:
        restart: always
        image: telegraf:latest
        user: "1000:1000"
        volumes:
            - ~/smarthome-docker/container/telegraf:/etc/telegraf
        networks:
            - smarthome-network

    deconz:
        restart: always
        image: marthoc/deconz
        expose:
            - "4000"
            - "4443"
        ports:
            - "4000:4000"
            - "4443:4443"
        privileged: true
        devices:
            - /dev/ttyACM0:/dev/ttyACM0
        volumes:
            - ~/smarthome-docker/container/deCONZ:/root/.local/share/dresden-elektronik/deCONZ
        networks:
            - smarthome-network
        environment:
            DECONZ_DEVICE: /dev/ttyACM0
            DECONZ_WEB_PORT: 4000
            DECONZ_WS_PORT: 4443
            TZ: Europe/Amsterdam

networks:
    smarthome-network:
        driver: bridge
